Repository ProjectYard/Art-Gallery, pull requests merged in 2022-10, with the labels that each got.

#1 Initial Running Setup
  artgallery/package-lock.json
  artgallery/package.json
  artgallery/src/App.css
  artgallery/src/App.js
  artgallery/src/Pages/Home.js
  artgallery/src/index.css
  artgallery/src/index.js
Labels: hacktoberfest

#2 Title and flex added
  artgallery/public/index.html
  artgallery/src/App.js
  artgallery/src/Pages/Home.css
  artgallery/src/Pages/Home.js
  artgallery/src/index.css
Labels: enhancement, hacktoberfest

#3 Post pages added
  artgallery/src/App.js
  artgallery/src/Pages/Page.css
  artgallery/src/Pages/Page.js
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#4 Contact Page Added
  artgallery/src/Pages/Contact.css
  artgallery/src/Pages/Contact.js
  artgallery/src/Pages/Page.css
  artgallery/src/Pages/Page.js
  artgallery/src/index.css
Labels: HACKTOBERFEST-ACCEPTED

#8 Modified Color
  artgallery/src/App.js
  artgallery/src/Pages/Page.css
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#9 Footer added
  artgallery/src/App.js
  artgallery/src/Pages/Footer.css
  artgallery/src/Pages/Footer.js
  artgallery/src/Pages/Page.js
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#10 Footer css
  artgallery/src/Pages/Footer.css
  artgallery/src/Pages/Footer.js
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#11 added content page
  artgallery/src/Pages/Footer.js
  artgallery/src/Pages/content.js
Labels: enhancement, HACKTOBERFEST-ACCEPTED
